### PR TITLE
Add learn caption for teacher file

### PR DESCRIPTION
**Pull request by githubteacher**
## Creating PR in order to merge change with master. Will likely need review in case something went wrong?

The changes I made are:
- Thing 1
- Thing 2
- Thing3

Tasks remaining:
- [x] Code review
- [x] More commits
- [x] Final review
- [x] Merge

cc: @aharshbe

### CODE REVIEW

**Comment by Meirzv** [comment]
Good Job 👋

**Review by Meirzv — APPROVED** [review]
Good job. Change is approved.

**Review by Meirzv — APPROVED** [review]
I already approved this request. 😠

**Review by kamanngpseg — APPROVED** [review]
APPROVED 👍

**Pull request merged**
